import AGWAccountAbi from '../abis/AGWAccount.js';
import {
  AGW_REGISTRY_ADDRESS,
  CANONICAL_DELEGATE_REGISTRY_ADDRESS,
  CANONICAL_EXCLUSIVE_DELEGATE_RESOLVER_ADDRESS,
  EOA_VALIDATOR_ADDRESS,
  SESSION_KEY_VALIDATOR_ADDRESS,
  SMART_ACCOUNT_FACTORY_ADDRESS,
} from '../constants.js';

export {
  AGWAccountAbi as AGWAccountAbi,
  AGW_REGISTRY_ADDRESS as agwRegistryAddress,
  CANONICAL_DELEGATE_REGISTRY_ADDRESS as delegateRegistryAddress,
  CANONICAL_EXCLUSIVE_DELEGATE_RESOLVER_ADDRESS as exclusiveDelegateResolverAddress,
  SESSION_KEY_VALIDATOR_ADDRESS as sessionKeyValidatorAddress,
  SMART_ACCOUNT_FACTORY_ADDRESS as smartAccountFactoryAddress,
  EOA_VALIDATOR_ADDRESS as validatorAddress,
};
